/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IRingBufferOverwriter } from "../IRingBufferOverwriter";

export class IRingBufferOverwriter__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRingBufferOverwriter {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IRingBufferOverwriter;
  }
}

const _abi = [
  {
    inputs: [
      {
        internalType: "bytes32",
        name: "_id",
        type: "bytes32",
      },
      {
        internalType: "uint256",
        name: "_index",
        type: "uint256",
      },
    ],
    name: "canOverwrite",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];
