/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface IRingBufferOverwriterInterface extends ethers.utils.Interface {
  functions: {
    "canOverwrite(bytes32,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "canOverwrite",
    values: [BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "canOverwrite",
    data: BytesLike
  ): Result;

  events: {};
}

export class IRingBufferOverwriter extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: IRingBufferOverwriterInterface;

  functions: {
    canOverwrite(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "canOverwrite(bytes32,uint256)"(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  canOverwrite(
    _id: BytesLike,
    _index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "canOverwrite(bytes32,uint256)"(
    _id: BytesLike,
    _index: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    canOverwrite(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    "canOverwrite(bytes32,uint256)"(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    canOverwrite(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "canOverwrite(bytes32,uint256)"(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    canOverwrite(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "canOverwrite(bytes32,uint256)"(
      _id: BytesLike,
      _index: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
